version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: akil
      POSTGRES_PASSWORD: root
      POSTGRES_DB: retails_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: 172.20.0.2

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      custom_network:
        ipv4_address: 172.20.0.3

volumes:
  postgres_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

